export const ALL_PRODS_REQ = "ALL_PRODS_REQ";
export const ALL_PRODS_SUCCESS = "ALL_PRODS_SUCCESS";
export const ALL_PRODS_FAILED = "ALL_PRODS_FAILED";


export const PROD_DETAILS_REQ = "PROD_DETAILS_REQ";
export const PROD_DETAILS_SUCCESS = "PROD_DETAILS_SUCCESS";
export const PROD_DETAILS_FAILED = "PROD_DETAILS_FAILED";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
